config/routes.rb
Rails.application.routes.draw do
  resources :animals
  get 'mammals', to: 'animals#mammals', as: 'mammals'
  get 'reptiles', to: 'animals#reptiles', as: 'reptiles'
  get 'birds', to: 'animals#birds', as: 'birds'

  root to: 'animals#homepage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @animals = Animal.all
  end

  def homepage;end

  def mammals
    @animals = Animal.all
    @mammals = @animals.where(classification: 'Ссавці')
  end

  def reptiles
    @animals = Animal.all
    @reptiles = @animals.where(classification: 'Рептилії')
  end

  def birds
    @animals = Animal.all
    @birds = @animals.where(classification: 'Птахи')
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:classification, :species, :type_, :order, :family, :genus, :description, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_animal_cards.erb
<div class="row row-cols-1 row-cols-md-3">
    <% locals[:animals].each do |animal| %>
        <div class="col mb-4">
            <div class="card h-100">
                <div class="view overlay">
                    <%= image_tag(animal.image.to_s, class: "card-img-top animals")%>
                    <div class="mask rgba-white-slight"></div>
                    </a>
                </div>

                <div class="card-body">
                    <h4 class="card-title"><%=animal.species%></h4>
                    <%=link_to "Більше", animal_path(animal), class: 'btn btn-primary btn-md'%>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/animals/_form.html.erb
<%= form_with(model: animal) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
        <% animal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :classification %>
    <%= form.text_field :classification %>
  </div>

  <div class="field">
    <%= form.label :species %>
    <%= form.text_field :species %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.text_field :order %>
  </div>

  <div class="field">
    <%= form.label :family %>
    <%= form.text_field :family %>
  </div>

  <div class="field">
    <%= form.label :genus %>
    <%= form.text_field :genus %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/_species.erb
<!-- Card deck -->
<div class="card-deck d-flex mt-5">
    <!-- Card -->
    <div class="card mb-4 species-card">
        <!--Card image-->
        <div class="view overlay">
            <%= image_tag("species/mammals", class: "card-img-top species-picture")%>
            <a href="#!">
                <div class="mask rgba-white-slight"></div>
            </a>
        </div>

        <!--Card content-->
        <div class="card-body d-flex flex-column">
            <h4 class="card-title">Ссавці</h4>
            <%=link_to "Проглянути", mammals_path, class: 'btn btn-primary btn-md'%>
        </div>

    </div>
    <!-- Card -->

    <!-- Card -->
    <div class="card mb-4 species-card">
        <!--Card image-->
        <div class="view overlay">
            <%= image_tag("species/reptiles", class: "card-img-top species-picture")%>

            <a href="#!">
                <div class="mask rgba-white-slight"></div>
            </a>
        </div>

        <div class="card-body d-flex flex-column">
            <h4 class="card-title">Рептилії</h4>
            <%=link_to "Проглянути", reptiles_path, class: 'btn btn-primary btn-md'%>
        </div>
        
    </div>
    <!-- Card -->

    <!-- Card -->
    <div class="card mb-4 species-card">
        <!--Card image-->
        <div class="view overlay">
            <%= image_tag("species/birds", class: "card-img-top species-picture")%>
            <a href="#!">
            <div class="mask rgba-white-slight"></div>
            </a>
        </div>


        <div class="card-body d-flex flex-column">
            <h4 class="card-title">Птахи</h4>
            <%=link_to "Проглянути", birds_path, class: 'btn btn-primary btn-md'%>
        </div>

    </div>
  <!-- Card -->

</div>
<!-- Card deck -->

app/views/animals/birds.erb
<div class="card bg-dark text-white">
  <%= image_tag("animals_banner_birds", class: "card-img")%>
  
  <div class="row card-img-overlay align-content-center">
    <h1 class=" display-1 card-title">Птахи</h1>
  </div>
</div>

<div class="container marketing">
    <%= render "animal_cards", locals: { animals: @birds }%>
</div>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/homepage.erb
<main>
  <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">
        <img src="https://scontent.fkbp1-1.fna.fbcdn.net/v/t39.30808-6/253337045_741605236795026_8341067661529761919_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=730e14&_nc_ohc=bTGM5VrStOUAX9O7z-q&_nc_ht=scontent.fkbp1-1.fna&oh=00_AT8OetFAavbgC1z0rvCW2acX21Z1gnOcFJBTP--RhpCFJw&oe=61F68E03" class="d-block w-100" >
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="https://scontent.fkbp1-1.fna.fbcdn.net/v/t1.6435-9/69756984_666213547203913_426981463607476224_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=e3f864&_nc_ohc=2zwmy5Nt7XUAX94pwOb&_nc_ht=scontent.fkbp1-1.fna&oh=00_AT-o0-QDHAnq1nbjYEiQwUva9MM2QaVvG_tOhwE8AmxvuA&oe=62187EF1" class="d-block w-100">
      </div>
      <div class="carousel-item">
        <%= image_tag("homepage/bear_and_wolf", class: "d-block w-100")%>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="container marketing">
    <hr class="featurette-divider">
    <div class="row featurette align-items-center">
      <div class="col-md-7 main-page-info">
        <h2 class="featurette-heading">Про нас</h2>
        <p class="lead">
          Регіональний зоопарк в Черкасах розмістився на 4,37 га,
          так що тваринам в неволі досить просторо. 
          Тут багато зелені, зустрічаються і рідкісні рослини, є озеро - справжній рай 
          для водоплавних птахів. Зоопарк є прекрасним місцем для сімейних прогулянок.
        </p>
      </div>
      <div class="col-md-5 order-md-1 main-page-picture">
        <%= render 'layouts/small_carousel', locales: {
          images: %w(
            homepage/about_us_1.jpg
            homepage/about_us_2.jpg
            homepage/about_us_3.jpg
          )
        }%>
      </div>
    </div>

    <hr class="featurette-divider">
    <div class="row featurette align-items-center">
      <div class="col-md-7 order-md-2 main-page-info">
        <h2 class="featurette-heading"> Наші улюбленці</h2>
        <p class="lead">
          Сьогодні тут міститься 240 видів представників фауни, понад півтори тисячі особин. 
          Це і ссавці, і птахи, і рептилії. Зоопарк спеціалізується на представниках 
          тераріумів групи і тварин лісової та лісостепової зон. 
          Навіть, півтораметровий нільський крокодил отримав простору «квартиру»
          з басейном.
        </p>
      </div>
      <div class="col-md-5 order-md-1 main-page-picture">
        <%= render 'layouts/small_carousel', locales: {
          images: %w(
            homepage/our_animals_1.jpg
            homepage/our_animals_2.jpg
            homepage/our_animals_3.jpg
          )
        }%>
      </div>
    </div>

    <hr class="featurette-divider">
    <div class="row featurette align-items-center">
      <div class="col-md-7 main-page-info">
        <h2 class="featurette-heading">Для дітей</h2>
        <p class="lead">
          У зоопарку є дитячий майданчик, який наразі реконструюють, і дитяче подвір’я, 
          де малеча може ближче познайомитися з домашніми тваринами.
        </p>
      </div>
      <div class="col-md-5 order-md-1 main-page-picture">
        <%= render 'layouts/small_carousel', locales: {
          images: %w(
            homepage/for_children_1.jpg
            homepage/for_children_2.jpg
            homepage/for_children_3.jpg
          )
        }%>
      </div>
    </div>
    <hr class="featurette-divider">
    <%= image_tag("zoo_map", class: "img-fluid w-100")%>
  </div>
</main>

app/views/animals/index.html.erb
<div class="card bg-dark text-white">
  <%= image_tag("animals_banner_1", class: "card-img")%>
  
  <div class="row card-img-overlay align-content-end">
    <h1 class=" display-1 card-title">Тварини</h1>
    <p id="subtitle" class="display-4">
      Понад двісті видів з усього світу
    </p>
  </div>
</div>

<div class="container marketing">
  <%= render "species" %>
</div>

app/views/animals/mammals.erb
<div class="card bg-dark text-white">
  <%= image_tag("animals_banner_mammals", class: "card-img")%>
  
  <div class="row card-img-overlay align-content-center">
    <h1 class=" display-1 card-title">Ссавці</h1>
  </div>
</div>

<div class="container marketing">
    <%= render "animal_cards", locals: { animals: @mammals }%>
</div>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/reptiles.erb
<div class="card bg-dark text-white">
  <%= image_tag("animals_banner_reptiles", class: "card-img")%>
  
  <div class="row card-img-overlay align-content-center">
    <h1 class=" display-1 card-title">Рептилії</h1>
  </div>
</div>

<div class="container marketing">
    <%= render "animal_cards", locals: { animals: @reptiles }%>
</div>

app/views/animals/show.html.erb
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <%= image_tag(@animal.image, class: "card-img")%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h1 class="card-title"><%= @animal.species %></h1>
        <ul class="list-group list-group-flush">

          <li class="list-group-item d-flex justify-content-between">
            <strong>Тип:</strong>
            <%= @animal.type_ %>
          </li>

          <li class="list-group-item d-flex justify-content-between">
              <strong>Клас:</strong>
              <%= @animal.classification %>
          </li>

          <li class="list-group-item d-flex justify-content-between">
            <strong>Ряд:</strong>
            <%= @animal.order %>
          </li>

          <li class="list-group-item d-flex justify-content-between">
            <strong>Родина:</strong>
            <%= @animal.family %>
          </li>

          <li class="list-group-item d-flex justify-content-between">
            <strong>Рід:</strong>
            <%= @animal.genus %>
          </li>

          <li class="list-group-item d-flex justify-content-between">
            <strong>Вид:</strong>
            <%= @animal.species %>
          </li>

        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container marketing">
  <h1 class="card-title">Основні характеристики</h1>
  <%= @animal.description %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <img src="https://rubarbs.com/media/case/block-ci-logo-284-155.png" width="50" height="64">
      <%end%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Тварини', animals_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Графік</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_small_carousel.erb
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag(locales[:images][0], width: "100%", height: "500px")%>
    </div>
    <div class="carousel-item">
      <%= image_tag(locales[:images][1], width: "100%", height: "500px")%>
    </div>
    <div class="carousel-item">
      <%= image_tag(locales[:images][2], width: "100%", height: "500px")%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zoo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %> 
    </header>

    <%= yield %>

  </body>
</html>